//===----------------------------------------------------------------------===//
//
// This source file is part of the swift-libp2p open source project
//
// Copyright (c) 2022-2026 swift-libp2p project authors
// Licensed under MIT
//
// See LICENSE for license information
// See CONTRIBUTORS for the list of swift-libp2p project authors
//
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

import Foundation

#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

/// This script fetches the latest [Multicodec table from the Multiformats repository](https://raw.githubusercontent.com/multiformats/multicodec/master/table.csv)
/// attempts to parse the data and generate an Enumeration from it.
///
/// To run this script and fetch the latest Multicodec values simply run the following command at the Multicodec project root
/// ```
/// swift run update-codecs
/// ```
/// This will overwrite the entire Codecs.swift file with the latest codecs.

// MARK: - Multiformat Codec Table Repository URL
var CSVDocumentURL = "https://raw.githubusercontent.com/multiformats/multicodec/master/table.csv"

// MARK: - Templates
let HEADER = """
    // swift-format-ignore-file
    //===----------------------------------------------------------------------===//
    //
    // This source file is part of the swift-libp2p open source project
    //
    // Copyright (c) 2022-2026 swift-libp2p project authors
    // Licensed under MIT
    //
    // See LICENSE for license information
    // See CONTRIBUTORS for the list of swift-libp2p project authors
    //
    // SPDX-License-Identifier: MIT
    //
    //===----------------------------------------------------------------------===//
    //
    // This file was generated automatically (do NOT modify this file)
    // Updated on {{+date_updated+}}

    import Foundation
    import VarInt

    /// An Enum for navigating supported Multiformat Codecs and their properties, most importantly their Name and Integer Code
    ///
    /// This enumeration is autogenerated from the [multicodec table repository](https://raw.githubusercontent.com/multiformats/multicodec/master/table.csv)
    ///
    /// To fetch the latest Multicodecs simply run the following cmd at the Multicodec package root
    /// ```
    /// swift run update-codecs
    /// ```
    ///
    /// - Warning: Not every entry in the table is settled. Check `status` before writing a Codec
    ///   into a new buffer: a `draft` Codec's code can still change, and a `deprecated` one might
    ///   have a replacement. Every Codec remains decodable either way, which is why the deprecated
    ///   ones are still made available.
    """

let ENUM_DEFINITION_TEMPLATE = """
    {{+enum_scope+}} enum {{+enum_title+}}{{+enum_rawType+}}{{+enum_protocols+}} {
        {{+enum_cases+}}
        {{+enum_additional_components+}}
        {{+enum_computed_properties+}}
        {{+enum_functions+}}
    }
    """

let ENUM_CASE = """
    case {{+case_title+}}{{+case_associatedValues+}}{{+case_rawValue+}}
    """

let ENUM_COMPUTED_PROPERTY = """
    {{+enum_scope+}} var {{+cp_title+}}: {{+cp_type+}} {
        switch self {
        {{+cp_case+}}
        {{+cp_default+}}
        }
    }
    """

let COMPUTED_PROPERTY_CASE = """
    case .{{+case_title+}}:
        return {{+case_value+}}
    """

let ENUM_ADDITIONAL_COMPONENTS = """

        /// Instantiation via the unsigned VarInt at the front of any byte collection
        /// ```
        ///  let p2p = try? Codecs(varInt: [0xa5, 0x03])
        /// ```
        {{+enum_scope+}} init(varInt bytes: some Collection<UInt8>) throws {
            guard let value = try? VarInt.decode(bytes).value, let s = Codecs(rawValue: value) else { throw MulticodecError.unknownCodecId }
            self = s
        }

        /// Instantiation via a Codec's integer code (ex: 0x70)
        {{+enum_scope+}} init(code: Int) throws {
            guard let raw = UInt64(exactly: code), let s = Codecs(rawValue: raw) else { throw MulticodecError.unknownCodecId }
            self = s
        }

        /// Instantiation via a Codec's integer code (ex: 0x70)
        {{+enum_scope+}} init(code: Int64) throws {
            guard let raw = UInt64(exactly: code), let s = Codecs(rawValue: raw) else { throw MulticodecError.unknownCodecId }
            self = s
        }

        /// Instantiation via a Codec's integer code (ex: 0x70)
        {{+enum_scope+}} init(code: UInt64) throws {
            guard let s = Codecs(rawValue: code) else { throw MulticodecError.unknownCodecId }
            self = s
        }

        /// Returns a list of all known Codec names
        {{+enum_scope+}} static var codecNames: [String] { return Codecs.allCases.map { $0.name } }

        /// Returns a list of all known Codec codes
        {{+enum_scope+}} static var codecCodes: [UInt64] { return Codecs.allCases.map { $0.rawValue } }
        
        /// Returns the code for this Codec
        {{+enum_scope+}} var code: UInt64 {
            return self.rawValue
        }

        /// Returns the code for this Codec as a VarInt Byte Buffer
        {{+enum_scope+}} var asVarInt: VarIntBytes { return self.rawValue.varIntBytes }
    """

// MARK: - Network Data Fetch
func fetchContents(url: String) -> String? {
    guard let u = URL(string: url) else {
        print("Invalid URL String")
        return nil
    }
    do {
        let data = try Data(contentsOf: u)
        let str = String(decoding: data, as: UTF8.self)
        //print(str)
        return str
    } catch {
        print("🚫 Error Fetching Contents at 🚫")
        print("URL: \(u.absoluteString)")
        print("Error: \(error.localizedDescription)")
        print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
    }
    return nil
}

// MARK: - CSV Parsing
struct CSVData {
    let rowNum: Int
    let columns: [(key: String, value: String)]
}

func parseStringIntoCSV(_ csv: String, headerRow: Int? = nil) -> [CSVData] {
    // Normalize CRLF/CR line endings so a trailing "\r" doesn't cling to the last column.
    let normalized = csv.replacingOccurrences(of: "\r\n", with: "\n").replacingOccurrences(of: "\r", with: "\n")
    var rows = normalized.split(separator: "\n")
    var headerKeys: [String] = []
    if let hr = headerRow, rows.count > hr {
        // Keep empty subsequences so column indices stay aligned with the header.
        headerKeys = rows[hr].split(separator: ",", omittingEmptySubsequences: false).map {
            stripLeadingSpaces(String($0))
        }
        rows.remove(at: hr)
    }
    // Cap the number of splits at one-per-column so commas inside the final column
    // (e.g. a codec's `description`) don't spill into phantom columns. `omittingEmptySubsequences: false`
    // preserves empty fields so `code`/`tag`/`description` never shift out of alignment.
    let maxSplits = headerKeys.isEmpty ? Int.max : headerKeys.count - 1
    return rows.enumerated().compactMap {
        CSVData(
            rowNum: $0.offset,
            columns: $0.element.split(separator: ",", maxSplits: maxSplits, omittingEmptySubsequences: false)
                .enumerated().map {
                    if headerKeys.count > $0.offset {
                        return (key: headerKeys[$0.offset], value: stripLeadingSpaces(String($0.element)))
                    } else {
                        return (key: "", value: stripLeadingSpaces(String($0.element)))
                    }
                }
        )
    }
}

func stripLeadingSpaces(_ str: String) -> String {
    var s = str
    while s.hasPrefix(" ") { s = String(s.dropFirst()) }
    return s
}

// MARK: - Enumeration Building Blocks
class EnumCase {
    let title: String
    let rawValue: String?
    let associatedValue: String?

    var computedProperties: [String: Any] = [:]

    init(title: String, rawValue: String) {
        self.title = title
        self.rawValue = rawValue
        self.associatedValue = nil
    }

    init(title: String, associatedValue: String) {
        self.title = title
        self.associatedValue = associatedValue
        self.rawValue = nil
    }

    init(title: String) {
        self.title = title
        self.associatedValue = nil
        self.rawValue = nil
    }
}

enum Scope: String {
    case INTERNAL = "internal"
    case OPEN = "open"
    case PUBLIC = "public"
    case PRIVATE = "private"
    case FILEPRIVATE = "fileprivate"
}

struct ComputedProperty {
    let title: String
    let type: Any
    let defaultValue: String
    let caseKey: String
    /// The Swift type to render, for types this script can't name (ex: `CodecTag?`)
    var typeName: String? = nil
    /// Renders a table value as the expression returned for that case. Defaults to a
    /// String literal for String typed properties, and the value verbatim otherwise.
    var renderValue: ((String) -> String)? = nil
}

/// Turns a table value into a valid Swift enum case name
func swiftCaseName(for value: String) -> String {
    let name = value.replacingOccurrences(of: "-", with: "_").replacingOccurrences(of: " ", with: "_")
    guard let first = name.first, first.isNumber else { return name }
    return "_" + name
}

/// Builds a String backed enum out of the distinct values found in one of the table's columns
///
/// The raw value is only spelled out when it differs from the case name, since a String
/// backed enum already defaults it's raw value to the case name.
func generateLookupEnum(title: String, documentation: String, values: [String], scope: Scope) -> String {
    let cases = values.map { value -> String in
        let caseName = swiftCaseName(for: value)
        return caseName == value ? "    case \(caseName)" : "    case \(caseName) = \"\(value)\""
    }
    return """

        \(documentation)
        \(scope.rawValue) enum \(title): String, CaseIterable, Sendable {
        \(cases.joined(separator: "\n"))
        }
        """
}

func generateEnum(
    scope: Scope,
    title: String,
    rawType: Any? = nil,
    protocolConformances: [String],
    cases: [EnumCase],
    computedProps: [ComputedProperty] = [],
    supportingTypes: [String] = []
) -> Data? {
    let dateFormatter = DateFormatter()
    dateFormatter.dateStyle = .short
    var e = HEADER.replacingOccurrences(of: "{{+date_updated+}}", with: dateFormatter.string(from: Date()))

    e = e + "\n" + ENUM_DEFINITION_TEMPLATE
    e = e.replacingOccurrences(of: "{{+enum_scope+}}", with: scope.rawValue)
    e = e.replacingOccurrences(of: "{{+enum_title+}}", with: title)  //Enforce CamelCase???
    if let rt = rawType {
        e = e.replacingOccurrences(of: "{{+enum_rawType+}}", with: ": \(rt.self)")
        if !protocolConformances.isEmpty {
            e = e.replacingOccurrences(
                of: "{{+enum_protocols+}}",
                with: protocolConformances.map { ", \($0)" }.joined()
            )
        } else {
            e = e.replacingOccurrences(of: "{{+enum_protocols+}}", with: "")
        }
    } else {
        e = e.replacingOccurrences(of: "{{+enum_rawType+}}", with: "")
        if !protocolConformances.isEmpty {
            e = e.replacingOccurrences(
                of: "{{+enum_protocols+}}",
                with: protocolConformances.enumerated().map {
                    if $0.offset == 0 { return ": \($0.element)" }
                    return ", \($0.element)"
                }.joined()
            )
        } else {
            e = e.replacingOccurrences(of: "{{+enum_protocols+}}", with: "")
        }
    }

    //Find the largest Key for formatting reasons...
    var largestKey = 0
    for c in cases {
        if c.title.count > largestKey { largestKey = c.title.count }
    }
    largestKey = largestKey + 1

    e = e.replacingOccurrences(
        of: "{{+enum_cases+}}",
        with: cases.map { generateCase($0, rawValueOffset: largestKey) }.joined(separator: "\n\t")
    )

    let additionalComponents = ENUM_ADDITIONAL_COMPONENTS.replacingOccurrences(
        of: "{{+enum_scope+}}",
        with: scope.rawValue
    )
    e = e.replacingOccurrences(of: "{{+enum_additional_components+}}", with: "\n\(additionalComponents)")

    if !computedProps.isEmpty {
        e = e.replacingOccurrences(
            of: "{{+enum_computed_properties+}}",
            with: computedProps.map {
                generateComputedProperty($0, cases: cases, scope: scope)
            }.joined(separator: "\n")
        )
    } else {
        e = e.replacingOccurrences(of: "{{+enum_computed_properties+}}", with: "")
    }
    e = e.replacingOccurrences(of: "{{+enum_functions+}}", with: "")
    //print(e)

    for supportingType in supportingTypes {
        e = e + "\n" + supportingType + "\n"
    }

    return e.data(using: .utf8)
}

func generateCase(_ enumCase: EnumCase, rawValueOffset: Int = 1) -> String {
    var c = ENUM_CASE
    c = c.replacingOccurrences(of: "{{+case_title+}}", with: enumCase.title)
    if let rv = enumCase.rawValue {
        c = c.replacingOccurrences(
            of: "{{+case_rawValue+}}",
            with: "\(String(repeating: " ", count: rawValueOffset - enumCase.title.count))= \(rv)"
        )
        c = c.replacingOccurrences(of: "{{+case_associatedValues+}}", with: "")
    } else if let av = enumCase.associatedValue {
        c = c.replacingOccurrences(of: "{{+case_associatedValues+}}", with: "(\(av))")
        c = c.replacingOccurrences(of: "{{+case_rawValue+}}", with: "")
    } else {
        c = c.replacingOccurrences(of: "{{+case_rawValue+}}", with: "")  //Set to empty
        c = c.replacingOccurrences(of: "{{+case_associatedValues+}}", with: "")  //Set to empty
    }
    return c
}

func generateComputedProperty(
    _ compProp: ComputedProperty,
    cases: [EnumCase],
    scope: Scope,
    depthIndent: Int = 1
) -> String {
    var cp = ENUM_COMPUTED_PROPERTY
    cp = cp.replacingOccurrences(of: "{{+enum_scope+}}", with: scope.rawValue)
    cp = cp.replacingOccurrences(of: "{{+cp_title+}}", with: compProp.title)

    var rawType = compProp.typeName ?? "\(compProp.type.self)"
    if rawType.contains("Optional<") {  // TODO: Nested Optionals Not Supported...
        rawType = rawType.replacingOccurrences(of: "Optional<", with: "")
        rawType = rawType.replacingOccurrences(of: ">", with: "?")
    }
    cp = cp.replacingOccurrences(of: "{{+cp_type+}}", with: rawType)

    var defaultNeeded: Bool = false
    let entries: [String] = cases.compactMap {
        // Empty values will fall through to the default case
        if let val = $0.computedProperties[compProp.caseKey], !"\(val)".isEmpty {
            var entry = COMPUTED_PROPERTY_CASE

            entry = entry.replacingOccurrences(of: "{{+case_title+}}", with: $0.title)

            if let render = compProp.renderValue {
                entry = entry.replacingOccurrences(of: "{{+case_value+}}", with: render("\(val)"))
            } else if rawType.lowercased().contains("string") {
                entry = entry.replacingOccurrences(of: "{{+case_value+}}", with: "\"\(val)\"")
            } else {
                entry = entry.replacingOccurrences(of: "{{+case_value+}}", with: "\(val)")
            }
            return entry
        }
        defaultNeeded = true
        return nil
    }
    if !entries.isEmpty {
        cp = cp.replacingOccurrences(
            of: "{{+cp_case+}}",
            with:
                "\(entries.joined(separator: "\n").replacingOccurrences(of: "\n", with: "\n\(String(repeating: "\t", count: depthIndent))"))"
        )
    } else {
        cp = cp.replacingOccurrences(of: "{{+cp_case+}}", with: "")
    }

    cp = cp.replacingOccurrences(
        of: "{{+cp_default+}}",
        with: defaultNeeded ? "default: return \(compProp.defaultValue)" : ""
    )

    cp = cp.replacingOccurrences(of: "\n", with: "\n\(String(repeating: "\t", count: depthIndent))")

    return "\n\(String(repeating: "\t", count: depthIndent))\(cp)"
}

// MARK: - Script to fetch CSV, Parse, Generate ENUM and update Codecs.swift...

/// Fetch CSV Data from repository
guard let str = fetchContents(url: CSVDocumentURL) else {
    exit(EXIT_FAILURE)
}
let entries = parseStringIntoCSV(str, headerRow: 0)

/// Itterate over the CSV data and extract out each Enum case
let enumCases: [EnumCase] = entries.compactMap {
    if let name = $0.columns.first(where: { $0.key == "name" })?.value,
        let rv = $0.columns.first(where: { $0.key == "code" })?.value
    {
        let ec = EnumCase(title: name.replacingOccurrences(of: "-", with: "_"), rawValue: rv)
        for col in $0.columns {
            ec.computedProperties[col.key] = col.value
        }
        return ec
    }
    return nil
}

guard !enumCases.isEmpty else {
    print("Codec table returned zero parseable results. Returning without updating.")
    exit(EXIT_FAILURE)
}

/// The distinct values of a column, sorted so that the generated output is stable between runs
func distinctValues(ofColumn column: String, in cases: [EnumCase]) -> [String] {
    Set(cases.compactMap { $0.computedProperties[column] as? String }.filter { !$0.isEmpty }).sorted()
}

let tags = distinctValues(ofColumn: "tag", in: enumCases)
let statuses = distinctValues(ofColumn: "status", in: enumCases)

/// Generate the necessary computed properties to match the table
///
/// `name` is generated from the table verbatim rather than derived from the case title.
/// The case title swaps every dash for an underscore, so deriving the name back out of it
/// would mangle the 20 codecs whose names legitimately contain an underscore
/// (ex: `bls12_381-g1-pub`, `jwk_jcs-pub`). Emitting literals also keeps `name` off of
/// `"\(self)"`, so a future `CustomStringConvertible` conformance can't silently change it.
let compPropName = ComputedProperty(title: "name", type: String.self, defaultValue: "\"\"", caseKey: "name")
/// `tag` and `status` are typed rather than strings.
/// Every row in the table is tagged today, but `tag` stays Optional so an untagged row can be
/// generated without inventing a category for it.
let compPropTag = ComputedProperty(
    title: "tag",
    type: String.self,
    defaultValue: "nil",
    caseKey: "tag",
    typeName: "CodecTag?",
    renderValue: { ".\(swiftCaseName(for: $0))" }
)
/// The table lists every codec's status, and treats an unlisted one as a draft.
let compPropStatus = ComputedProperty(
    title: "status",
    type: String.self,
    defaultValue: ".draft",
    caseKey: "status",
    typeName: "CodecStatus",
    renderValue: { ".\(swiftCaseName(for: $0))" }
)
/// The generated property is named `details` rather than `description`, both because
/// it's optional and to leave `description` free for `CustomStringConvertible`.
/// `caseKey` still points at the table's 'description' column.
let compPropDes = ComputedProperty(
    title: "details",
    type: Optional<String>.self,
    defaultValue: "nil",
    caseKey: "description"
)

/// Generate the final Enum
guard
    let data = generateEnum(
        scope: .PUBLIC,
        title: "Codecs",
        rawType: UInt64.self,
        protocolConformances: ["CaseIterable", "Equatable", "Sendable"],
        cases: enumCases,
        computedProps: [compPropName, compPropTag, compPropStatus, compPropDes],
        supportingTypes: [
            generateLookupEnum(
                title: "CodecTag",
                documentation: """
                    /// The category a Codec belongs to, as designated by the multicodec table
                    ///
                    /// ```swift
                    /// let protocols = Codecs.codecs(tagged: .multiaddr)
                    /// ```
                    """,
                values: tags,
                scope: .PUBLIC
            ),
            generateLookupEnum(
                title: "CodecStatus",
                documentation: """
                    /// How settled a Codec's entry in the multicodec table is
                    ///
                    /// - Warning: A `draft` Codec's code is not guaranteed to be stable, and a
                    ///   `deprecated` one shouldn't be written into new buffers. Both remain
                    ///   decodable, since buffers written against them still exist.
                    """,
                values: statuses,
                scope: .PUBLIC
            ),
        ]
    )
else {
    print("Failed to generate Codecs enumeration. Returning without updating.")
    exit(EXIT_FAILURE)
}

/// Write Data to Codecs.swift...
guard
    let codecsURL = URL(
        string: "Sources/Multicodec/Codecs.swift",
        relativeTo: URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
    )
else {
    print("Failed to locate the local Codecs.swift file for update. Returning without updating.")
    exit(EXIT_FAILURE)
}

do {
    try data.write(to: codecsURL)
    print("Updated Codecs Successfully!")
    exit(EXIT_SUCCESS)
} catch {
    print("Error Updating Codecs.swift -> \(error.localizedDescription)")
    exit(EXIT_FAILURE)
}
